### Create a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json
{
  "email": "admin@gmail.com",
  "password": "123456"
}
### get categories
DELETE http://localhost:3000/api/gallery/3
### get question paper
GET http://localhost:3000/api/questionBank
###
GET http://localhost:3000/api/auth/me
###
GET http://localhost:3000/api/masterData/years 
###
DELETE http://localhost:3000/api/questionBank/1
